CREATE DATABASE ptg
USE ptg

CREATE TABLE ESCALA (
    VALORESCALA FLOAT
)

CREATE TABLE TRANSLACAO (
    EIXOX FLOAT,
    EIXOY FLOAT
)

CREATE TABLE ROTACAO (
    GRAU FLOAT
)

==========================
SELECT * FROM ESCALA
SELECT * FROM TRANSLACAO
SELECT * FROM ROTACAO